// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZeKju.Data.Contexts;

#nullable disable

namespace ZeKju.Data.Migrations
{
    [DbContext(typeof(ZeKjuContext))]
    [Migration("20230318192302_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZeKju.Domain.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("flight_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirlineId")
                        .HasColumnType("int")
                        .HasColumnName("airline_id");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("arrival_time");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("departure_time");

                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("route_id");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("Flights", (string)null);
                });

            modelBuilder.Entity("ZeKju.Domain.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("route_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("departure_date");

                    b.Property<int>("DestinationCityId")
                        .HasColumnType("int")
                        .HasColumnName("destination_city_id");

                    b.Property<int>("OriginCityId")
                        .HasColumnType("int")
                        .HasColumnName("origin_city_id");

                    b.HasKey("Id");

                    b.ToTable("Routes", (string)null);
                });

            modelBuilder.Entity("ZeKju.Domain.Subscription", b =>
                {
                    b.Property<int>("AgencyId")
                        .HasColumnType("int")
                        .HasColumnName("agency_id");

                    b.Property<int>("OriginCityId")
                        .HasColumnType("int")
                        .HasColumnName("origin_city_id");

                    b.Property<int>("DestinationCityId")
                        .HasColumnType("int")
                        .HasColumnName("destination_city_id");

                    b.HasKey("AgencyId", "OriginCityId", "DestinationCityId");

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("ZeKju.Domain.Flight", b =>
                {
                    b.HasOne("ZeKju.Domain.Route", "TheRoute")
                        .WithMany("Flights")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TheRoute");
                });

            modelBuilder.Entity("ZeKju.Domain.Route", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
